[versions]
agp = "8.13.2"
kotlin = "2.2.21"
appcompat = "1.7.1"
fragment = "1.8.9"
material = "1.14.0-alpha07"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }